#!/bin/zsh

. ~/.zsh/vars

alias zreload=". ~/.zshrc"

alias c="clear"
alias l="ls -l"
alias ll='ls -ahlG | less; echo "\e[1;32m --[\e[1;34m Dirs:\e[1;36m `ls -al | egrep \"^drw\" | wc -l` \e[1;32m|\e[1;35m Files: \e[1;31m`ls -al | egrep -v \"^drw\" | grep -v total | wc -l` \e[1;32m]--"'
alias v="vim"
alias vi=vim
alias cdc="cd; clear"
alias t="tmux"

function gcm() { git commit -m "$1" }

alias cp="cp -v"
alias ls="ls -hFG"
alias mmv="noglob zmv -W"
alias grep="grep --color=auto"

alias jqflat="jq --stream -r flat"
jqpager() {
    jq -C "$@" | less -R
}

alias -g L="| less"
alias -g H="| head"
alias -g T="| tail"
alias -g G="| grep"
alias -g E="| egrep"
alias -g S="| sed -r -e"
alias -g J="| jq"
alias -g JL="| jqpager"
