#!/bin/zsh
#
export PATH=$PATH:~/bin:/sbin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/java/jre/bin:/opt/mozilla/bin:.
export PATH=/opt/homebrew/bin:$PATH

export EDITOR=vim
export PYTHONSTARTUP=~/.pystartup

# I dislike how virtualenv inserts something at the beginning of the prompt.
# I disable it here and use a two-line prompt that displays it at the end
# of the first line.
export VIRTUAL_ENV_DISABLE_PROMPT=1
