#!/bin/zsh
#
# reload zshrc
function src()
{
        autoload -U zrecompile
                [[ -f ~/.zshrc ]] && zrecompile -p ~/.zshrc
				for i in "$(find ~/.zsh/ -type f)"; do
					[[ -f $i ]] && zrecompile -p $i
					[[ -f $i.zwc.old ]] && rm -f $i.zwc.old
				done
                [[ -f ~/.zcompdump ]] && zrecompile -p ~/.zcompdump
                [[ -f ~/.zcompdump ]] && zrecompile -p ~/.zcompdump
                [[ -f ~/.zshrc.zwc.old ]] && rm -f ~/.zshrc.zwc.old
                [[ -f ~/.zcompdump.zwc.old ]] && rm -f ~/.zcompdump.zwc.old
                source ~/.zshrc
}

